language: node_js
node_js:
  - "node"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "6.0"
  - "6.4"
  - "iojs"
  - "iojs-v2.4.0"
  - "iojs-v3.2.0"

notifications:
  email: ["andri@dot.ee"]
